### ISSUE TITLE
English is not default language for unsupported local

### ISSUE THREAD

**Issue by hrdyy** [b3dgs/lionengine-editor#4]
## Expected Behavior
Showing Menu Titles

## Actual Behavior
NLS MissingWarning

## Steps to Reproduce the Problem
Open the Programm

## Specifications

  - LionEngine Version: 9
  - JDK: 8
  - OS: Ubuntu 18.04 & Windows 10 Pro

**Comment by DjThunder** [comment]
Can you join a screenshot ? I can't find it on my local install. Thanks in advance.

**Comment by hrdyy** [comment]
http://prntscr.com/mu7td8

its the same on Ubuntu 18.04

**Comment by DjThunder** [comment]
Ah I see, you may use a local which is not 'en' nor 'fr'.
It should be english by default if not supported... but it's not the case indeed.

@hrdyy Quick fix for you, add this to LionEngine Editor.ini
`-vmargs
-Duser.language=en
`

I will fix it later.
